@startuml SPRING_CLOUD_SLEUTH
!theme sketchy-outline
title spring cloud sleuth
skinparam interface {
}
skinparam component {
   backgroundColor LightSteelBlue
   FontSize 14
   ArrowFontSize 14
   ArrowFontColor #777777
   ArrowColor #FF6655
}

component sws[
   sleuth-waiter-service
   waiter service 添加seuth 链路追踪
]

component mzbs[
   mq-zipkin-barista-service
   barista service 添加seuth 链路追踪 mq消息
]

component scs[
   sleuth-customer-service
   customer service 添加sleuth 链路追踪
]
@enduml
