@startuml ACTUATOR_MODULE
!theme sketchy-outline
title actuator module
[indicator-demo] as id
[metrics-demo] as md
note bottom of id
    添加Health 指标
end note

note bottom of md
  metrics 配置 以及counter的展示
end note

@enduml
