@startuml CONFIGURATION_MODULE
!theme sketchy-outline
title configuration module
[autoconfigure-demo] as ad
[demo-spring-autoconfiguration-greeting] as dge
[demo-spring-boot-autoconfigure] as dsa
[demo-spring-autoconfigure-backport] as dacb
[demo-spring-boot-starter] as dsbs

[property-source-demo] as psd
note bottom of dge
   被实际调用的bean
end note
note bottom of dsa
   自动装配项目通过自动配置加载对应实例
end note
note bottom of ad
   实际调用类 可以通过引用jar或者打开配置来获取
   demo-spring-autoconfiguration-greeting的实例
end note
note bottom of dacb
   老版本的spring 通过bean注册来实现自动配置
end note

note bottom of dsbs
做为starter 引入其他两个项目的依赖
end note
dsbs->dge:pom
dsbs->dsa:pom
ad->dsbs:pom
ad ->dsa:jar 
dsa ->dge:jar 
ad ->dacb:jar

note bottom of psd
   Spring boot 自定义配置属性加载
end note
@enduml
