@startuml SPRING_CLOUD_STUDY_MODULE
!theme sketchy-outline
title spring cloud module
skinparam interface {
}
skinparam component {
   backgroundColor LightSteelBlue
   FontSize 14
   ArrowFontSize 14
   ArrowFontColor #777777
   ArrowColor #FF6655
}
package "spring-cloud-netflix"{
   component esd[
   eureka-server-demo
   eureka的服务注册中心
   ]

   component ews[
   eureka-waiter-service
   注册eureka的服务
   ]
   component lbcs[
   load-balance-customer-service
   spring cloud负载均衡
   因为ribbon在新版本给砍掉了  spring cloud自己出手
   ]
   ews --> esd
   lbcs --> esd:load balance request waiter service
}
component fcs[
   feign-customer-service
   使用 open feign 来实现客户端调用
]
 fcs->esd:使用feign调用服务

package "spring-cloud-zookeeper"{
   component zk[
   zookeeper
   ]
   component zws[
   zk-waiter-service
   注册zookeeper的服务
   ]

   component zcs[
   zk-customer-service
   使用zookeeper的客户端
   ]
   zws --> zk
   zcs --> zk
}

package "spring-cloud-consul"{
   component cs[
   consul
   ]
   component cws[
   consul-waiter-service
   注册consul的服务
   ]

   component ccs[
   consul-customer-service
   使用consul的客户端
   ]
   cws --> cs
   ccs --> zk
}
@enduml
