@startuml SPRING_CLOUD_STREAM
!theme sketchy-outline
title spring cloud stream
skinparam interface {
}
skinparam component {
   backgroundColor LightSteelBlue
   FontSize 14
   ArrowFontSize 14
   ArrowFontColor #777777
   ArrowColor #FF6655
}

package "rabbit mq"{
   component   rbs[
   rabbitmq-barista-service
    接收消息的咖啡师
   ]
   component rws[
   rabbitmq-waiter-service
    发送消息的服务员
   ]
   rws -> rbs
   rbs ->rws
   component   fprbs[
   fp-rabbitmq-barista-service
    函数式编程接收消息的咖啡师
   ]
   component fprws[
   fp-rabbitmq-waiter-service
    函数式编程发送消息的服务员
   ]
   fprws -> fprbs
   fprbs ->fprws

   component bws[
      busy-waiter-service
       通知客户的服务员
      ]
   bws-->rbs:通知订单支付

}
component lcs[
     lazy-customer-service
      接收通知的客户
     ]
bws-->lcs:消息通知取走快递
package "kafka"{
   component kbs[
      kafka-barista-service
      通过Kafka发送订阅消息的 咖啡师
   ]
   component kws[
      kafka-waiter-service
      通过Kafka发送订阅消息的 服务人员
   ]
}

component scs[
      scheduled-customer-service
      通过schedule 轮询订阅订单状态
   ]
scs->kws
kws -->kbs
kbs-->kws
scs ->db:查询状态

@enduml
