@startuml SPRING_CONFIG_SERVER
!theme sketchy-outline
title spring config server
skinparam interface {
}
skinparam component {
   backgroundColor LightSteelBlue
   FontSize 14
   ArrowFontSize 14
   ArrowFontColor #777777
   ArrowColor #FF6655
}

package "spring-cloud-nacos"{
   component   cs[
   config-server
   使用git来搭建本地配置服务
   ]
   component gcws[
   git-config-waiter-service
    配置服务客户端,通过git配置中心获取配置
   ]
   gcws -> cs
}


@enduml
