spring:
  application:
    name: plsql
  datasource:
    #中文
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.3:5432/postgres
    username: postgres
    password: kuka
    initial-size: 8
    min-idle: 5
    max-active: 10
    query-timeout: 6000
    transaction-query-timeout: 6000
    remove-abandoned-timeout: 1800
    initialization-mode: always
server:
  port:7777
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  typeAliasesPackage: com.fantasybaby.mybatis.plsql.demo.entity
  configuration:
    map-underscore-to-camel-case: true